meta:
  author: Roger Luo
  title: Half Integer
  subtitle: 'Physics, Life, Computing'
  description: Roger Luo's Blog

url: rogerluo.me
github: Roger-luo

# Structure
dir:
  public: public
  source:
    post: post
    slide: slide
  media: media
  code: code

markdown:
  extensions:
    - markdown.extensions.extra
    - pymdownx.arithmatex
    - pymdownx.magiclink

reveal:
  theme: black
  url: 'https://github.com/hakimel/reveal.js/archive/3.6.0.tar.gz'
  config:
    controls: false
    progress: true
    slideNumber: false
    history: true
    keyboard: true
    overview: true
    center: true
    touch: true
    loop: false
    rtl: false
    fragments: true
    help: true
    showNotes: false
    autoSlide: 0
    autoSlideStoppable: true
    mouseWheel: false
    hideAddressBar: true
    previewlinks: false
    transition: 'default'
    transitionSpeed: 'default'
    backgroundTransition: 'default'
    viewDistance: 3
    parallaxBackgroundImage: ''
    parallaxBackgroundSize: ''
    parallaxBackgroundHorizontal: ''
    parallaxBackgroundVertical: ''
